import type { CatalogEntry } from './types';
import { TankArenaArt } from './art/TankArenaArt';
import { TreasureQuestArt } from './art/TreasureQuestArt';
import { OAnQuanArt } from './art/OAnQuanArt';
import { UtilityArt, EducationArt, ArcadeArt } from './art/PlaceholderArt';
import { SudokuCubeArt } from './art/SudokuCubeArt';
import { BugMinerArt } from './art/BugMinerArt';
import { F1RacingArt } from './art/F1RacingArt';
import { TopdownAdventureArt } from './art/TopdownAdventureArt';
import { PuzzleGameKidsArt } from './art/PuzzleGameKidsArt';
import { BeHocVuiArt } from './art/BeHocVuiArt';
import { TinyPirateQuestArt } from './art/TinyPirateQuestArt';
import { ArrowfallArt } from './art/ArrowfallArt';
import { SmashStressArt } from './art/SmashStressArt';

export const REGISTRY: CatalogEntry[] = [
  {
    id: 'tankarena',
    title: 'Tank Arena',
    description: 'Bắn tăng LAN kiểu Battle City — 4–16 người, 3D, host authoritative.',
    category: 'game',
    path: '/games/tankarena/',
    accent: '#7ee29b',
    pluginId: 'tankarena',
    Art: TankArenaArt,
  },
  {
    id: 'treasurequest',
    title: 'Treasure Quest',
    description: 'Thám hiểm giáo dục — quiz checkpoint, đường đi phân nhánh, kho báu chung.',
    category: 'game',
    path: '/games/treasurequest/',
    accent: '#f0b866',
    pluginId: 'treasurequest',
    Art: TreasureQuestArt,
  },
  {
    id: 'oanquan',
    title: 'Ô ăn quan',
    description: 'Ô ăn quan dân gian — cờ 2 người theo lượt trên bàn 3D.',
    category: 'game',
    path: '/games/oanquan/',
    accent: '#6ee2d6',
    pluginId: 'oanquan',
    Art: OAnQuanArt,
  },
  {
    id: 'sudokucube',
    title: 'Mini Sudoku Cube',
    description: 'Sudoku 4x4 trên 6 mặt khối lập phương 3D.',
    category: 'game',
    path: '/games/sudokucube/',
    accent: '#3b82f6',
    pluginId: 'sudokucube',
    Art: SudokuCubeArt,
  },
  {
    id: 'bugminer',
    title: 'Bug Miner',
    description: 'Game 3D multiplayer 1v1 lấy cảm hứng từ Đào Vàng. Chế độ PvP: Developer vs QC.',
    category: 'game',
    path: '/games/bugminer/',
    accent: '#ffcc00',
    pluginId: 'bugminer',
    authorTag: 'Made with love by Trang',
    badge: 'NEW',
    Art: BugMinerArt,
  },
  {
    id: 'f1racing',
    title: 'F1 Racing',
    description: 'Đua F1 LAN 3D — qualifying, grid theo best lap, tối đa 10 tay đua.',
    category: 'game',
    path: '/games/f1racing/',
    accent: '#e10600',
    pluginId: 'f1racing',
    badge: 'NEW',
    Art: F1RacingArt,
  },
  {
    id: 'topdownadventure',
    title: 'Topdown Adventure',
    description: 'Game phiêu lưu góc nhìn từ trên xuống (Web HTML5).',
    category: 'game',
    path: '/?play=topdownadventure',
    accent: '#4ade80',
    isHtmlEmbed: true,
    externalUrl: 'https://nhanptn1.github.io/topdownadventure/',
    badge: 'HOT',
    Art: TopdownAdventureArt,
  },
  {
    id: 'scoreboard',
    title: 'Bảng điểm',
    description: 'Bảng điểm chung cho cả buổi chơi cùng nhau.',
    category: 'utility',
    path: '/apps/scoreboard/',
    accent: '#6c8cff',
    comingSoon: true,
    Art: UtilityArt,
  },
  {
    id: 'quiz',
    title: 'Quiz nhanh',
    description: 'Câu đố nhanh cho gia đình và lớp học.',
    category: 'education',
    path: '/apps/quiz/',
    accent: '#9f6cff',
    comingSoon: true,
    Art: EducationArt,
  },
  {
    id: 'puzzlegamekids',
    title: 'Ghép hình vui nhộn',
    description: 'Trò chơi ghép hình kết hợp học kiến thức cho bé.',
    category: 'education',
    path: '/?play=puzzlegamekids',
    accent: '#E8A23C',
    authorTag: 'Made with love by Mai',
    isHtmlEmbed: true,
    externalUrl: '/html-games/puzzle-game-kids/index.html',
    badge: 'NEW',
    Art: PuzzleGameKidsArt,
  },
  {
    id: 'behocvui',
    title: 'Bé Học Vui',
    description: 'Vừa chơi vừa học chữ cái và số đếm cùng những người bạn đáng yêu!',
    category: 'education',
    path: '/?play=behocvui',
    accent: '#ec4899',
    authorTag: 'Made by Phú',
    isHtmlEmbed: true,
    externalUrl: 'https://education-game-sigma.vercel.app',
    badge: 'NEW',
    Art: BeHocVuiArt,
  },
  {
    id: 'tinypiratequest',
    title: 'Tiny Pirate Quest',
    description: 'Hành trình truy tìm kho báu của hải tặc tí hon - Thu thập tiền vàng, tìm mảnh bản đồ và chiêu mộ thủy thủ.',
    category: 'game',
    path: '/?play=tinypiratequest',
    accent: '#f59e0b',
    isHtmlEmbed: true,
    externalUrl: 'https://sherryonline.github.io/tiny-pirate-quest/',
    authorTag: 'Made with love by Ngoc Sherry',
    badge: 'NEW',
    Art: TinyPirateQuestArt,
  },
  {
    id: 'arrowfall',
    title: 'ARROWFALL (Endless Siege)',
    description: 'The horde never stops. From the shattered sky they descend — slimes, beasts, cursed knights, and towering elemental Overlords — and only one archer stands between them and the world below. You cannot retreat. You cannot rest. You can only aim. Draw from four mastered disciplines — Physical precision, searing Fire, freezing Frost, and chaining Lightning — and forge your own legend as Ranger, Sniper, Elementalist, or Juggernaut. Dash through danger, unleash devastating ultimates, and climb an endless gauntlet of ever-deadlier waves.',
    category: 'game',
    path: '/?play=arrowfall',
    accent: '#6366f1',
    isHtmlEmbed: true,
    externalUrl: 'https://nhanptn1.github.io/enlessactionrpg',
    authorTag: 'Made By Nhân',
    badge: 'NEW',
    Art: ArrowfallArt,
  },
  {
    id: 'smashstress',
    title: 'SmashStress (Relief Your Stress)',
    description: 'Giải tỏa căng thẳng với tựa game đập phá cực đã. Đập tan mọi lo âu mệt mỏi của bạn!',
    category: 'arcade',
    path: '/?play=smashstress',
    accent: '#ef4444',
    isHtmlEmbed: true,
    externalUrl: 'https://smashstress.vercel.app/',
    authorTag: 'Made By Tuấn Anh',
    badge: 'NEW',
    Art: SmashStressArt,
  },
  {
    id: 'caro',
    title: 'Cờ caro',
    description: 'Cờ caro chạy ngay trên trình duyệt, không cần server.',
    category: 'arcade',
    path: '/apps/caro/',
    accent: '#ff7e9b',
    comingSoon: true,
    Art: ArcadeArt,
  },
];
